#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Replace version with bumped one
if [[ -n $(git diff --cached --name-only "*.sass") ]]; then
    git diff --cached --name-only "*.sass" | xargs -I% node $(dirname "$0")/bump.js %
    cd $(dirname "$0"); yarn build; git reset .;
    echo "The userstyles version bumped. Please stage files again."
    exit 1;
fi
